spring: 
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-aos:5432/aos_db}
    username: ${SPRING_DATASOURCE_USERNAME:aos_pg}
    password: ${SPRING_DATASOURCE_PASSWORD:Maryame1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    open-in-view: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: ALWAYS
      data-locations: classpath:data.sql,classpath:data-services.sql
      platform: POSTGRESQL
  mail: 
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ${SENDGRID_API_KEY}
    protocol: smtp
    properties: 
      mail: 
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true
  web: 
    resources:
      static-locations: file:uploads/
  mvc: 
    static-path-pattern: /static/**
application:
  security:
    jwt:
      secret-key: 0Xft560/AaGtvlV7KqGlKPj8pBRubzWYxzGpvgg0LyRZdAi3WksRrhCq5myck+hJ
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4201/activate-account
server:
  port: 8089

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: ALWAYS


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tryItOutEnabled: true

app: 
  upload: 
    dir: uploads
    max-file-size: 10MB
    allowed-extensions: pdf,jpg,jpeg,png,doc,docx