services:
  postgres:
    container_name: postgres-aos_PUBLIC
    image: postgres:15
    environment:
      POSTGRES_USER: aos_pg
      POSTGRES_PASSWORD: Maryame1234
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: aos_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - aos_network_PUBLIC

    
    

  backend:
    container_name: backend_PUBLIC
    build:
      context: ./aos_backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/aos_db
      SPRING_DATASOURCE_USERNAME: aos_pg
      SPRING_DATASOURCE_PASSWORD: Maryame1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      SPRING_MAIL_HOST: smtp.sendgrid.net
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_PROTOCOL: smtp
      SPRING_MAIL_USERNAME: apikey
      SPRING_MAIL_PASSWORD: ${SENDGRID_API_KEY}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
      APPLICATION_MAILING_FRONTEND_ACTIVATION_URL: http://localhost:4200/activate-account
    ports:
      - "8089:8089"
    depends_on:
      - postgres 
    env_file:
      - .env
    networks:
      - aos_network_PUBLIC

  frontend:
    container_name: frontend_PUBLIC
    build:
      context: ./aos_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
      
    networks:
      - aos_network_PUBLIC

networks:
  aos_network_PUBLIC:
    driver: bridge

volumes:
  postgres:
    driver: local